name: Test yugabytedb-action

on:
  push:

jobs:
  test-yugabytedb-action:
    runs-on: ubuntu-latest
    container:
      image: yugabytedb/yugabyte:latest
      ports:
        - 7000
        - 9000
        - 5433
        - 9042
      options: --entrypoint bin/yugabyted start --daemon=false
    steps: 
    - name: Test YSQL API
      run: docker run --network host --rm yugabytedb/yugabyte-client:latest ysqlsh -h localhost -p "${{ steps.server.outputs.ysql_port }}" -c \\conninfo

    - name: Test YCQL API
      run: docker run --network host --rm yugabytedb/yugabyte-client:latest ycqlsh localhost "${{ steps.server.outputs.ycql_port }}" --execute 'SHOW HOST'

    - name: Test YB Master UI
      run: curl --head "http://localhost:${{ steps.server.outputs.yb_master_ui_port }}"

    - name: Test YB Tserver UI
      run: curl --head "http://localhost:${{ steps.server.outputs.yb_tserver_ui_port }}"
